#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Husky"

cp -Rf ../DnD/Characters/ ./src/characters
cp -Rf ../DnD/Setting/ ./src/setting
cp -Rf ../DND.SRD.Wiki/Documents/ ./src/core

git add src/core/*
git add src/characters/*
git add src/setting/*
